### PR TITLE
Add Android 81

### PR DESCRIPTION
**Pull request by Hypnosphi**
```
 % npx browserslist 'last 1 android version'
android 81
```

### CODE REVIEW

**Comment by zloirock** [comment]
Thanks for the PR, but in `core-js` `android > 4.4.4` [already handled as the related chrome version](https://github.com/zloirock/core-js/blob/ebddf97e642c37257e9ef8f6359ecea3226da253/packages/core-js-compat/targets-parser.js#L54-L56).

**Comment by Hypnosphi** [comment]
@zloirock babel packages [use](https://github.com/babel/babel/search?q=core-js-compat)  `core-js-compat/data` directly. What do you think is the best course of actions for them in order to support modern android?

**Comment by zloirock** [comment]
I think that it should be resolved on the Babel targets parser side. Makes no sense to have a separate field in compat data for modern Android since the modern Android browser is just Chrome.

**Comment by zloirock** [comment]
Ok, I'll move it directly to compat data for consistency and preventing questions why old android web view in compat data json, but modern - not.

**Pull request closed without merging**
