### PR TITLE
Add typescript declarations for core-js-compat

### PR DESCRIPTION
**Pull request by susnux**
Reuse it for the core-js-builder declarations to prevent duplicated code

### CODE REVIEW

**Comment by zloirock** [comment]
Thanks! However, `core-js-compat` contains some more entries.

**Comment by susnux** [comment]
@zloirock I have added more type declarations, but do you think type declarations for the `helpers` are required as well?

**Comment by zloirock** [comment]
> (CI fails because of a NodeJS bug [nodejs/node#47505](https://github.com/nodejs/node/issues/47505), I'll add a workaround soon.)

Added a workaround in `master`.

**Comment by susnux** [comment]
@zloirock 
> Added a workaround in `master`.

Rebased works now.

**Pull request merged**
