### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by tomByrer**
Sorry brother!

### CODE REVIEW

**Review by methbkts — APPROVED** [review]

**Comment by rybak** [comment]
@zloirock and @methbkts would you be interested in a bigger PR to proof-read and fix grammar in `docs/2023-02-14-so-whats-next.md` and `README.md`?

**Comment by zloirock** [comment]
@rybak why not? Thanks.

**Comment by rybak** [comment]
@Luashine hello. You can find my work in progress here: https://github.com/zloirock/core-js/compare/master...rybak:core-js:grammar-fixes. I've gone through everything until "Roadmap".

**Comment by Luashine** [comment]
@rybak I'm literally done :) I will post the PR as is and go to bed, if there're any improvements to be made then feel free to do whatever improve upon further or undo my changes.

Sorry, I've checked out your fork before but I don't think I looked at branches before I commented above. That's in case you had already started working by then.

**Comment by rybak** [comment]
@Luashine 

> @rybak I'm literally done :) I will post the PR as is and go to bed, if there're any improvements to be made then feel free to do whatever improve upon further or undo my changes.

Thank you for working on this.

> Sorry, I've checked out your fork before but I don't think I looked at branches before I commented above. That's in case you had already started working by then.

No worries.

**Pull request merged**
