### PR TITLE
feat: add array.groupByMap

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by Jack-Works** [comment]
That proposal also adds https://tc39.es/proposal-array-grouping/#sec-array.prototype.groupbymap but no `%TypedArray%.prototype.groupBy`

**Comment by zloirock** [comment]
Thanks! It's already tracked here https://github.com/zloirock/core-js/pull/1001

**Comment by Jack-Works** [comment]
I have removed TypedArray.groupBy

**Comment by zloirock** [comment]
@Jack-Works it's a breaking change, so it can be removed only in `core-js@4`.

**Comment by Jack-Works** [comment]
> @Jack-Works it's a breaking change, so it can be removed only in `core-js@4`.

I reverted that change. Do core-js provide semver constraints even for proposals? I thought proposals are unstable

**Comment by zloirock** [comment]
Yes, sure. Breaking changes can be only in cases that *most likely* still no one used, like removing `@@species` support from `Array.prototype.groupBy` in #1001. Removing `esnext.typed-array.group-by` will break too many cases of code generated by `@babel/preset-env`.

**Comment by zloirock** [comment]
Published.

**Pull request merged**
