### PR TITLE
Fix the format and translation of Chinese markdown

### PR DESCRIPTION
**Pull request by cotes2020**
What has been changed:
- fix Chinese and English mixed formatting
- fix bold/heading syntax error
- improved translation of word `bus factor` in "so-whats-next.md"
- added internal translation links

-----

Most of them are fixed by lint tool, and the remaining parts that cannot be detected are fixed manually. Although it cannot be guaranteed to be 100% perfect, it has significantly improved the reading experience compared to the original version.

### CODE REVIEW

**Comment by cotes2020** [comment]
As an additional suggestion, should a multilingual translation link be added to the EN markdown docs, pointing to other multilingual versions of markdown docs?

For instance, add the following to the head of  file `docs/2023-02-14-so-whats-next.md`:

```md
Translations: [zh_CN](docs/zh_CN/2023-02-14-so-whats-next.md.md)
```

**Comment by zloirock** [comment]
Yep, that makes sense.

**Comment by cotes2020** [comment]
OK, will do

**Comment by cotes2020** [comment]
I have done all the editing and this PR is open for review.

**Comment by santi100a** [comment]
@zloirock, consider merging this pull request, it is green.

**Pull request closed without merging**
