### PR TITLE
test: test on Linux, macOS and Windows

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by zloirock** [comment]
I'm not sure why it's required.

**Comment by zloirock** [comment]
Ok, feel free to make it work. That could be useful only for testing of the builder - main tests use `phantomjs`. Also, please, don't add `yarn.lock` to the repo.

**Comment by DanielRuf** [comment]
Understood.

**Comment by zloirock** [comment]
👍

**Pull request merged**
